fix(devbox): Fix devbox scripts call base on repo root
When call script `devbox run test`, the call of the script
`./resources/scripts/test.sh`, last line of `.devbox/gen/script/test.sh` is
relative the directory `.devbox/gen/script`.

So, when runnin `devbox run test` from the root of the git directory, devbox
return this error :

```
/home/rdeville/git/misc/docker-gcp-private-mirror/.devbox/gen/scripts/test.sh: line 7: ./resources/scripts/test.sh: cannot execute: required file not found
Error: error running script "test" in Devbox: exit status 127
```

This PR fix this issues by calling `resources/scripts/*` absolute based
on the root of the git directory.